# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_auto_20170206_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='id_game',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='save',
            name='game_board',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='save',
            unique_together=set([('user', 'game')]),
        ),
    ]
