# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170208_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Save_game', to='game.Game'),
        ),
    ]
